"""Deterministic dark-mode PNG charts for Telegram delivery."""

from __future__ import annotations

from io import BytesIO
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import mplfinance as mpf

INK = "#08110f"
PANEL = "#101a17"
TEXT = "#e8eee9"
MUTED = "#8ca097"
GRID = "#26332e"
GREEN = "#39d98a"
RED = "#ff5c7a"
COLORS = ["#d9ff57", "#58d6ff", "#ff8d6b", "#c9a7ff", "#f9d65c", "#72e6a6"]


def candlestick_png(frame: Any, symbol: str, period: str) -> bytes:
    market = mpf.make_marketcolors(
        up=GREEN, down=RED, edge="inherit", wick="inherit", volume="inherit"
    )
    style = mpf.make_mpf_style(
        base_mpf_style="nightclouds",
        marketcolors=market,
        facecolor=INK,
        figcolor=INK,
        gridcolor=GRID,
        gridstyle="--",
        rc={"font.family": "DejaVu Sans", "axes.labelcolor": MUTED, "xtick.color": MUTED,
            "ytick.color": MUTED},
    )
    averages = tuple(window for window in (20, 50) if len(frame) >= window)
    options = {
        "type": "candle",
        "volume": True,
        "style": style,
        "title": f"\n{symbol} · {period.upper()} · OHLCV",
        "ylabel": "Price",
        "ylabel_lower": "Volume",
        "figsize": (12, 7.5),
        "returnfig": True,
        "tight_layout": True,
    }
    if averages:
        options["mav"] = averages
    fig, axes = mpf.plot(frame, **options)
    axes[0].title.set_color(TEXT)
    _source(fig, "Yahoo Finance · generated by Atlas")
    return _png(fig)


def performance_png(frames: dict[str, Any], period: str) -> bytes:
    aligned = _aligned_closes(frames)
    indexed = aligned.divide(aligned.iloc[0]).multiply(100)
    fig, axis = _canvas(f"Relative performance · {period.upper()}", "Indexed return (start = 100)")
    for index, symbol in enumerate(indexed.columns):
        axis.plot(indexed.index, indexed[symbol], color=COLORS[index % len(COLORS)],
                  linewidth=2.2, label=symbol)
    axis.axhline(100, color=MUTED, linewidth=0.8, alpha=0.6)
    _legend(axis)
    _source(fig, "Yahoo Finance · normalized close prices")
    return _png(fig)


def correlation_png(frames: dict[str, Any], period: str) -> bytes:
    closes = _aligned_closes(frames)
    matrix = closes.pct_change(fill_method=None).dropna().corr()
    if len(matrix) < 2:
        raise ValueError("correlation heatmaps require at least two symbols with overlapping data")

    fig, axis = plt.subplots(figsize=(9.5, 8), facecolor=INK)
    axis.set_facecolor(PANEL)
    image = axis.imshow(matrix.values, vmin=-1, vmax=1, cmap="RdYlGn")
    labels = list(matrix.columns)
    axis.set_xticks(range(len(labels)), labels=labels, color=TEXT)
    axis.set_yticks(range(len(labels)), labels=labels, color=TEXT)
    axis.set_title(f"Daily-return correlation · {period.upper()}", color=TEXT, loc="left", pad=18,
                   fontsize=17, fontweight="bold")
    for row in range(len(labels)):
        for column in range(len(labels)):
            value = matrix.iloc[row, column]
            axis.text(column, row, f"{value:.2f}", ha="center", va="center",
                      color="#06100c" if abs(value) < 0.65 else "white", fontweight="bold")
    colorbar = fig.colorbar(image, ax=axis, fraction=0.046, pad=0.04)
    colorbar.ax.tick_params(colors=MUTED)
    for spine in axis.spines.values():
        spine.set_color(GRID)
    fig.tight_layout(rect=(0, 0.05, 1, 1))
    _source(fig, "Yahoo Finance · Pearson correlation of daily close-to-close returns")
    return _png(fig)


def _aligned_closes(frames: dict[str, Any]):
    import pandas as pd

    series = [frame["Close"].rename(symbol) for symbol, frame in frames.items()]
    aligned = pd.concat(series, axis=1, join="inner").dropna()
    if len(aligned) < 2:
        raise ValueError("not enough overlapping price history")
    return aligned


def _canvas(title: str, ylabel: str):
    fig, axis = plt.subplots(figsize=(12, 7), facecolor=INK)
    axis.set_facecolor(PANEL)
    axis.set_title(title, color=TEXT, loc="left", pad=16, fontsize=17, fontweight="bold")
    axis.set_ylabel(ylabel, color=MUTED)
    axis.grid(True, color=GRID, linestyle="--", linewidth=0.7, alpha=0.8)
    axis.tick_params(colors=MUTED)
    for spine in axis.spines.values():
        spine.set_color(GRID)
    fig.tight_layout(rect=(0, 0.05, 1, 1))
    return fig, axis


def _legend(axis: Any) -> None:
    legend = axis.legend(facecolor=PANEL, edgecolor=GRID, framealpha=1, ncol=3)
    for label in legend.get_texts():
        label.set_color(TEXT)


def _source(fig: Any, text: str) -> None:
    fig.text(0.012, 0.012, text, color=MUTED, fontsize=9)


def _png(fig: Any) -> bytes:
    output = BytesIO()
    try:
        fig.savefig(output, format="png", dpi=150, facecolor=fig.get_facecolor(), bbox_inches="tight")
        return output.getvalue()
    finally:
        plt.close(fig)
